"""Lawful forensic extraction services for non-rooted and rooted Android devices."""

from .agent_apk import (
    AgentCollector,
    AgentExtractionResult,
    AgentInstaller,
    AgentInstallerConfig,
    CollectorConfig,
    InstallResult,
)
from .apk_downgrade import (
    APK_DOWNGRADE_PROFILES,
    ApkDowngradeExtractor,
    ApkDowngradeProfile,
    ApkDowngradeResult,
    PreservedApk,
    get_apk_downgrade_profile,
)
from .cloud import (
    CloudBackupRouter,
    CloudBackupRouterResult,
    CloudTokenBundle,
    GoogleBackupResult,
    GoogleBackupToken,
    GoogleTakeoutDownloader,
    WhatsAppBackupResult,
    WhatsAppCloudDownloader,
    WhatsAppCloudToken,
)
from .hardware import (
    ChipsetFamily,
    ChipsetProbe,
    KeyBlobMetadata,
    KeystoreExtractor,
    KeystoreInspectionResult,
    LockScreenProfile,
    LockType,
    MtkBromAcquisitionResult,
    MtkBromExtractor,
    PhysicalAcquisitionRouter,
    PhysicalAcquisitionRouterResult,
    PitRecord,
    QualcommEdlAcquisitionResult,
    QualcommEdlExtractor,
    RouterConfig,
    SamsungDownloadModeExtractor,
    SamsungDownloadModeResult,
    ScreenLockAssessmentService,
    SpreadtrumBootromExtractor,
    UnisocFdlAcquisitionResult,
    WipeRisk,
    detect_chipset_from_usb,
    hdlc_decode,
    hdlc_encode,
    parse_pit,
)
from .signal_rooted import SignalExtractionResult, SignalRootedExtractor
from .sqlite_carver import CarvedFragment, CarvingResult, SQLiteCarver
from .streaming_manifest import ExtractionManifest, ManifestEntry, StreamingManifestCollector
from .telegram_rooted import TelegramExtractionResult, TelegramRootedExtractor
from .whatsapp_downgrade import WhatsAppDowngradeExtractor, WhatsAppDowngradeResult

__all__ = [
    # Hardware acquisition
    "ChipsetFamily",
    "ChipsetProbe",
    "KeyBlobMetadata",
    "KeystoreExtractor",
    "KeystoreInspectionResult",
    "LockScreenProfile",
    "LockType",
    "MtkBromAcquisitionResult",
    "MtkBromExtractor",
    "PhysicalAcquisitionRouter",
    "PhysicalAcquisitionRouterResult",
    "PitRecord",
    "QualcommEdlAcquisitionResult",
    "QualcommEdlExtractor",
    "RouterConfig",
    "SamsungDownloadModeExtractor",
    "SamsungDownloadModeResult",
    "ScreenLockAssessmentService",
    "SpreadtrumBootromExtractor",
    "UnisocFdlAcquisitionResult",
    "WipeRisk",
    "detect_chipset_from_usb",
    "hdlc_decode",
    "hdlc_encode",
    "parse_pit",
    # Existing extractors
    "CarvedFragment",
    "APK_DOWNGRADE_PROFILES",
    "ApkDowngradeExtractor",
    "ApkDowngradeProfile",
    "ApkDowngradeResult",
    "CarvingResult",
    "ExtractionManifest",
    "ManifestEntry",
    "PreservedApk",
    "SignalExtractionResult",
    "SignalRootedExtractor",
    "SQLiteCarver",
    "StreamingManifestCollector",
    "TelegramExtractionResult",
    "TelegramRootedExtractor",
    "WhatsAppDowngradeExtractor",
    "WhatsAppDowngradeResult",
    "AgentCallLog",
    "AgentCollector",
    "AgentContact",
    "AgentExtractionResult",
    "AgentInstalledApp",
    "AgentInstaller",
    "AgentInstallerConfig",
    "AgentSms",
    "CloudBackupRouter",
    "CloudBackupRouterResult",
    "CloudTokenBundle",
    "CollectorConfig",
    "GoogleBackupResult",
    "GoogleBackupToken",
    "GoogleTakeoutDownloader",
    "InstallResult",
    "WhatsAppBackupResult",
    "WhatsAppCloudDownloader",
    "WhatsAppCloudToken",
    "get_apk_downgrade_profile",
]

