"""Deterministic, injection-safe JSON, CSV, and PDF report renderers."""

import csv
import io
from collections.abc import Callable
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from .snapshot import ReportSnapshot


def render_json(snapshot: ReportSnapshot) -> bytes:
    return snapshot.model_dump_json(indent=2).encode("utf-8")


def render_csv(snapshot: ReportSnapshot) -> bytes:
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\r\n")
    writer.writerow(
        (
            "record_origin",
            "artifact_id",
            "evidence_reference_id",
            "title",
            "category",
            "subtype",
            "status",
            "source_locator",
            "detected_mime",
            "size_bytes",
            "sha256",
            "event_or_collected_at",
            "parser",
            "confidence",
            "bookmark_reason",
            "tags",
            "analyst_notes",
            "summary",
        )
    )
    for artifact in snapshot.selected_artifacts:
        writer.writerow(
            tuple(
                neutralize_csv(value)
                for value in (
                    "adb_acquired_file",
                    artifact.id,
                    artifact.evidence_file_id,
                    artifact.title,
                    artifact.category,
                    "file",
                    artifact.status,
                    artifact.source_relative_path,
                    artifact.detected_mime,
                    str(artifact.size_bytes),
                    artifact.sha256,
                    artifact.collected_at.isoformat(),
                    "forensix.file_normalizer",
                    "high",
                    artifact.bookmark_reason or "",
                    "; ".join(artifact.tags),
                    " | ".join(artifact.analyst_notes),
                    "",
                )
            )
        )
    for imported_artifact in snapshot.imported_artifacts:
        writer.writerow(
            tuple(
                neutralize_csv(value)
                for value in (
                    "imported_source_parser",
                    imported_artifact.id,
                    imported_artifact.evidence_source_id,
                    imported_artifact.title,
                    imported_artifact.category,
                    imported_artifact.subtype,
                    imported_artifact.status,
                    imported_artifact.source_locator,
                    "",
                    "",
                    imported_artifact.artifact_hash,
                    (
                        imported_artifact.event_time.isoformat()
                        if imported_artifact.event_time
                        else ""
                    ),
                    f"{imported_artifact.parser_id}@{imported_artifact.parser_version}",
                    imported_artifact.confidence,
                    "",
                    "",
                    "",
                    imported_artifact.summary,
                )
            )
        )
    return output.getvalue().encode("utf-8")


def neutralize_csv(value: str) -> str:
    if value.startswith(("=", "+", "-", "@", "\t", "\r")):
        return f"'{value}"
    return value


class _InvariantCanvas(canvas.Canvas):  # type: ignore[misc]
    def __init__(self, *args: object, **kwargs: object) -> None:
        kwargs["invariant"] = 1
        super().__init__(*args, **kwargs)


def render_pdf(snapshot: ReportSnapshot) -> bytes:
    buffer = io.BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=20 * mm,
        bottomMargin=18 * mm,
        title=f"ForensiX Preliminary Report - {snapshot.case.case_number}",
        author="ForensiX",
        subject="Preliminary Android logical triage report",
    )
    styles = _styles()
    story: list[object] = []
    story.extend(
        (
            Paragraph("FORENSIX", styles["brand"]),
            Paragraph("PRELIMINARY FORENSIC TRIAGE REPORT", styles["report_title"]),
            Spacer(1, 6 * mm),
            _warning_box(snapshot.report.preliminary_warning, styles),
            Spacer(1, 8 * mm),
            _key_value_table(
                (
                    ("Case number", snapshot.case.case_number),
                    ("Case title", snapshot.case.title),
                    ("Case status", snapshot.case.status),
                    ("Generated by", snapshot.report.generated_by_name),
                    ("Generated at", snapshot.report.generated_at.isoformat()),
                    ("Report ID", snapshot.report.report_id),
                    (
                        "Schema / template",
                        f"{snapshot.schema_version} / {snapshot.template_version}",
                    ),
                    ("Tool version", snapshot.tool_version),
                ),
                styles,
            ),
            Spacer(1, 6 * mm),
            Paragraph(
                "This report is a preliminary triage output and is not a claim of completeness, "
                "physical acquisition, hardware write blocking, or legal admissibility.",
                styles["body"],
            ),
            PageBreak(),
        )
    )
    _section(story, "1. Case information", styles)
    story.append(
        _key_value_table(
            (
                ("Description", snapshot.case.description or "Not provided"),
                ("Legal authority reference", snapshot.case.legal_authority or "Not provided"),
                ("Case created", snapshot.case.created_at.isoformat()),
            ),
            styles,
        )
    )
    _section(story, "2. Device and readiness summary", styles)
    if not snapshot.devices:
        story.append(Paragraph("No assessed device is recorded for this case.", styles["body"]))
    for device in snapshot.devices:
        story.append(
            _key_value_table(
                (
                    (
                        "Device",
                        " ".join(filter(None, (device.manufacturer, device.model))) or "Unknown",
                    ),
                    ("Serial", f"ending {device.serial_suffix}"),
                    (
                        "Android / SDK",
                        f"{device.android_version or 'Unknown'} / {device.sdk_level or 'Unknown'}",
                    ),
                    ("Security patch", device.security_patch or "Unknown"),
                    ("Build fingerprint", device.build_fingerprint or "Unknown"),
                ),
                styles,
            )
        )
        story.append(Spacer(1, 3 * mm))
    _section(story, "3. Acquisition scope", styles)
    if not snapshot.acquisitions:
        story.append(Paragraph("No acquisition plan is recorded.", styles["body"]))
    for acquisition in snapshot.acquisitions:
        story.append(
            _key_value_table(
                (
                    ("Scope", acquisition.scope),
                    ("Modules", ", ".join(acquisition.modules) or "None"),
                    ("Inventory status", acquisition.inventory_status or "Not run"),
                    ("Inventory manifest", acquisition.inventory_manifest_hash or "Not available"),
                    ("Plan hash", acquisition.plan_hash),
                ),
                styles,
            )
        )
        story.append(Spacer(1, 3 * mm))
    _section(story, "4. Evidence Twin imported sources", styles)
    if not snapshot.evidence_sources:
        story.append(Paragraph("No imported evidence source is recorded.", styles["body"]))
    for source in snapshot.evidence_sources:
        story.append(
            _key_value_table(
                (
                    ("Source", source.display_name),
                    ("Declared origin", source.source_type),
                    ("Acquisition classification", source.acquisition_level),
                    ("Container / status", f"{source.container_format} / {source.status}"),
                    ("Size", str(source.size_bytes or "Unknown")),
                    ("Master SHA-256", source.sha256 or "Not available"),
                    ("Chunk ledger SHA-256", source.chunks_sha256 or "Not available"),
                    ("Manifest SHA-256", source.manifest_sha256 or "Not available"),
                    ("Working copies", str(len(source.working_copies))),
                    ("Verification records", str(len(source.verifications))),
                    ("Parser runs", str(len(source.parser_runs))),
                    ("Sealed tool outputs", str(len(source.tool_outputs))),
                ),
                styles,
            )
        )
        for limitation in source.limitations:
            story.append(Paragraph(f"- {escape(limitation)}", styles["small"]))
        if source.parser_runs:
            parser_rows = [["Parser", "Status", "Artifacts", "Run / program hash"]]
            parser_rows.extend(
                [
                    f"{run.parser_id}@{run.parser_version}",
                    run.status,
                    str(run.artifact_count),
                    (f"{run.run_hash} / {run.execution_detail.get('program_sha256', 'built-in')}"),
                ]
                for run in source.parser_runs
            )
            story.append(_data_table(parser_rows, (52 * mm, 22 * mm, 20 * mm, 78 * mm), styles))
        if source.tool_outputs:
            output_rows = [["Derived output", "Size", "SHA-256"]]
            output_rows.extend(
                [item.relative_path, str(item.size_bytes), item.sha256]
                for item in source.tool_outputs[:100]
            )
            story.append(_data_table(output_rows, (62 * mm, 24 * mm, 86 * mm), styles))
        story.append(Spacer(1, 3 * mm))
    _section(story, "5. Evidence summary", styles)
    story.append(
        _key_value_table(
            tuple(
                (category.title(), str(count))
                for category, count in sorted(snapshot.evidence_summary.items())
            )
            or (("Artifacts", "0"),),
            styles,
        )
    )
    story.append(Paragraph("Selected/bookmarked artifacts", styles["subheading"]))
    if snapshot.selected_artifacts:
        rows = [["Title", "Category", "Size", "SHA-256"]]
        rows.extend(
            [artifact.title, artifact.category, str(artifact.size_bytes), artifact.sha256]
            for artifact in snapshot.selected_artifacts[:100]
        )
        story.append(_data_table(rows, (58 * mm, 24 * mm, 22 * mm, 68 * mm), styles))
    else:
        story.append(
            Paragraph("No active bookmarks were selected for this report.", styles["body"])
        )
    story.append(Paragraph("Imported-source parsed artifacts", styles["subheading"]))
    if snapshot.imported_artifacts:
        imported_rows = [["Title", "Type", "Confidence", "Parser"]]
        imported_rows.extend(
            [
                item.title,
                item.subtype,
                item.confidence,
                f"{item.parser_id}@{item.parser_version}",
            ]
            for item in snapshot.imported_artifacts[:100]
        )
        story.append(_data_table(imported_rows, (58 * mm, 30 * mm, 24 * mm, 60 * mm), styles))
    else:
        story.append(Paragraph("No imported-source artifacts are recorded.", styles["body"]))
    _section(story, "6. Timeline summary", styles)
    if snapshot.timeline:
        rows = [["Time", "Type", "Confidence", "Summary"]]
        rows.extend(
            [item.event_time.isoformat(), item.timestamp_type, item.confidence, item.summary]
            for item in snapshot.timeline[:100]
        )
        story.append(_data_table(rows, (42 * mm, 38 * mm, 24 * mm, 68 * mm), styles))
    else:
        story.append(Paragraph("No timeline events are recorded.", styles["body"]))
    _section(story, "7. Integrity and custody", styles)
    story.append(
        _key_value_table(
            tuple(
                (status.title(), str(count))
                for status, count in sorted(snapshot.integrity_summary.items())
            )
            or (("Verification records", "0"),),
            styles,
        )
    )
    story.append(Paragraph(f"Custody events included: {len(snapshot.custody)}", styles["body"]))
    _section(story, "8. Methodology", styles)
    story.extend(Paragraph(f"- {escape(item)}", styles["body"]) for item in snapshot.methodology)
    _section(story, "9. Errors and limitations", styles)
    if snapshot.errors:
        story.append(Paragraph("Recorded errors", styles["subheading"]))
        story.extend(Paragraph(f"- {escape(item)}", styles["error"]) for item in snapshot.errors)
    story.append(Paragraph("Known limitations", styles["subheading"]))
    story.extend(Paragraph(f"- {escape(item)}", styles["body"]) for item in snapshot.limitations)
    story.append(Spacer(1, 6 * mm))
    story.append(
        Paragraph(
            "The SHA-256 of this PDF is stored alongside the report after rendering and is not "
            "embedded inside the hashed PDF bytes.",
            styles["small"],
        )
    )
    footer: Callable[[canvas.Canvas, object], None] = _footer
    document.build(story, onFirstPage=footer, onLaterPages=footer, canvasmaker=_InvariantCanvas)
    return buffer.getvalue()


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "brand": ParagraphStyle(
            "Brand",
            parent=base["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=14,
            textColor=colors.HexColor("#0891B2"),
            alignment=TA_CENTER,
        ),
        "report_title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0F172A"),
            alignment=TA_CENTER,
        ),
        "heading": ParagraphStyle(
            "Heading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            spaceBefore=12,
            spaceAfter=7,
            textColor=colors.HexColor("#0F172A"),
        ),
        "subheading": ParagraphStyle(
            "Subheading",
            parent=base["Heading3"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=13,
            spaceBefore=8,
            spaceAfter=4,
            textColor=colors.HexColor("#164E63"),
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#334155"),
            alignment=TA_LEFT,
        ),
        "small": ParagraphStyle(
            "Small",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=7,
            leading=9,
            textColor=colors.HexColor("#64748B"),
        ),
        "error": ParagraphStyle(
            "Error",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=colors.HexColor("#991B1B"),
        ),
        "warning": ParagraphStyle(
            "Warning",
            parent=base["BodyText"],
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#78350F"),
            alignment=TA_CENTER,
        ),
        "table": ParagraphStyle(
            "Table",
            parent=base["BodyText"],
            fontName="Helvetica",
            fontSize=7,
            leading=9,
            textColor=colors.HexColor("#334155"),
        ),
    }


def _section(story: list[object], title: str, styles: dict[str, ParagraphStyle]) -> None:
    story.append(Paragraph(escape(title), styles["heading"]))


def _warning_box(value: str, styles: dict[str, ParagraphStyle]) -> Table:
    table = Table([[Paragraph(escape(value), styles["warning"])]], colWidths=(172 * mm,))
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FEF3C7")),
                ("BOX", (0, 0), (-1, -1), 0.8, colors.HexColor("#F59E0B")),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ]
        )
    )
    return table


def _key_value_table(
    items: tuple[tuple[str, str], ...], styles: dict[str, ParagraphStyle]
) -> Table:
    rows = [
        [
            Paragraph(f"<b>{escape(label)}</b>", styles["table"]),
            Paragraph(escape(value), styles["table"]),
        ]
        for label, value in items
    ]
    table = Table(rows, colWidths=(46 * mm, 126 * mm), repeatRows=0)
    table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F1F5F9")),
                ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD5E1")),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    return table


def _data_table(
    rows: list[list[str]], widths: tuple[float, ...], styles: dict[str, ParagraphStyle]
) -> Table:
    rendered = [[Paragraph(escape(str(value)), styles["table"]) for value in row] for row in rows]
    table = Table(rendered, colWidths=widths, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#164E63")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#CBD5E1")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), (colors.white, colors.HexColor("#F8FAFC"))),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    return table


def _footer(pdf: canvas.Canvas, document: object) -> None:
    page_number = getattr(document, "page", 1)
    pdf.saveState()
    pdf.setStrokeColor(colors.HexColor("#CBD5E1"))
    pdf.line(18 * mm, 14 * mm, 192 * mm, 14 * mm)
    pdf.setFont("Helvetica-Bold", 7)
    pdf.setFillColor(colors.HexColor("#B45309"))
    pdf.drawString(18 * mm, 9 * mm, "PRELIMINARY - CONTROLLED LOGICAL TRIAGE")
    pdf.setFont("Helvetica", 7)
    pdf.setFillColor(colors.HexColor("#64748B"))
    pdf.drawRightString(192 * mm, 9 * mm, f"Page {page_number}")
    pdf.restoreState()
