"""Typed, policy-bounded Android Debug Bridge access."""

from .client import AdbClient, SystemAdbClient
from .diagnostics import AdbDiagnostic, diagnose_adb
from .discovery import AdbBinaryResolver
from .errors import (
    AdbBinaryNotFoundError,
    AdbCommandError,
    AdbDeviceNotAuthorizedError,
    AdbDeviceNotFoundError,
    AdbError,
    AdbOutputLimitError,
    AdbTimeoutError,
    AdbTransferLimitError,
)
from .mock import MockAdbClient, MockAdbScenario
from .models import (
    AdbServerInfo,
    ContentProviderAccessProbe,
    ContentProviderAccessStatus,
    ContentProviderQueryResult,
    ContentProviderRecord,
    DeviceState,
    DeviceTransport,
    PhysicalBlockCaptureResult,
    PhysicalBlockProbe,
    PulledFileResult,
    RootAccessProbe,
    RootAccessStatus,
    RootedBundleResult,
    SharedStorageRootProbe,
    StorageInventoryEntry,
    StorageInventoryResult,
    StorageProbeStatus,
)
from .policy import (
    CONTENT_PROVIDER_MAX_RECORDS,
    INVENTORY_MAX_DEPTH,
    INVENTORY_MAX_ITEMS,
    MAX_ACQUIRED_FILE_BYTES,
    MAX_PHYSICAL_BLOCK_BYTES,
    MAX_ROOTED_BUNDLE_BYTES,
    AdbCommandPolicy,
    AdbOperation,
    ApprovedAdbCommand,
    ContentProviderProfile,
    PhysicalBlockProfile,
    RootedCollectionProfile,
    SharedStorageRoot,
)
from .runner import AdbCommandResult, SubprocessAdbRunner
from .validation_fixture import (
    KNOWN_FILE_FIXTURE_ID,
    KNOWN_FILE_RELATIVE_PATH,
    KNOWN_FILE_SHA256,
    KNOWN_FILE_SIZE_BYTES,
    known_file_payload,
    write_known_file_fixture,
)

__all__ = [
    "AdbBinaryNotFoundError",
    "AdbBinaryResolver",
    "AdbDiagnostic",
    "AdbClient",
    "AdbCommandError",
    "AdbCommandResult",
    "AdbCommandPolicy",
    "AdbDeviceNotAuthorizedError",
    "AdbDeviceNotFoundError",
    "AdbError",
    "INVENTORY_MAX_DEPTH",
    "INVENTORY_MAX_ITEMS",
    "CONTENT_PROVIDER_MAX_RECORDS",
    "KNOWN_FILE_FIXTURE_ID",
    "KNOWN_FILE_RELATIVE_PATH",
    "KNOWN_FILE_SHA256",
    "KNOWN_FILE_SIZE_BYTES",
    "MAX_ACQUIRED_FILE_BYTES",
    "MAX_PHYSICAL_BLOCK_BYTES",
    "MAX_ROOTED_BUNDLE_BYTES",
    "AdbOutputLimitError",
    "AdbTransferLimitError",
    "AdbOperation",
    "AdbServerInfo",
    "AdbTimeoutError",
    "DeviceState",
    "DeviceTransport",
    "ContentProviderAccessProbe",
    "ContentProviderAccessStatus",
    "ContentProviderQueryResult",
    "ContentProviderRecord",
    "ContentProviderProfile",
    "PhysicalBlockCaptureResult",
    "PhysicalBlockProbe",
    "PulledFileResult",
    "RootAccessProbe",
    "RootAccessStatus",
    "RootedBundleResult",
    "MockAdbClient",
    "MockAdbScenario",
    "ApprovedAdbCommand",
    "PhysicalBlockProfile",
    "RootedCollectionProfile",
    "SharedStorageRoot",
    "SharedStorageRootProbe",
    "StorageInventoryEntry",
    "StorageInventoryResult",
    "StorageProbeStatus",
    "SubprocessAdbRunner",
    "SystemAdbClient",
    "diagnose_adb",
    "known_file_payload",
    "write_known_file_fixture",
]
